language: java
jdk:
- oraclejdk7
sudo: false
branches:
  only:
  - master
before_install:
- mkdir -p ~/.m2; wget -q -O ~/.m2/settings.xml https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/travis_maven_settings_simple.xml
script: mvn clean install deploy
env:
  global:
  - secure: qVobkcWS4BgttEtry2bwo9ge3NkgtvBWlqnPfuVnyerZk2UjmozT7ENDSKzwaz+eeht2pOCsjJIbxJ/Nwal70XsqN4Xl+kgSaBVj5/g9z1kijBMhSsKi93s8rTsJrlLxdmAatpbRlM3eFc/JRFmH4P+tCcHXjUGB4PjI7YGOSG0d9TCCgaq9gGeiH/Z1FcFSxkralB5/lHGIdCBecmWvwatA+KctOpPTbSvNz9a/sJXjGe+F9r0pmV5wMFBo/sukxln8cjJVSkNfJQ4ltBSKCPkLsjKx2GcMbF2AbF4HwOeUg1+eJB9wSrgZ24nrKTkJih/3nqciQx997c7E0KNjPH4EXFW8r7e4G8wYc7J3pD8lPfW93l4+vyRuCQRfdbDtds3se3+/pXQwO3ltMbmc1yqXcOEWyEz593ZL6P8svY0aLzrjgBEMZdkCwzaPYKQo0YG8n43jO4V9vuuqpu0eyfkYr9hLAR6hNQnAyhDUn5QRfT2jSlVlUzuWevmQjFLV8Fxhm3umAjyHCq9wVWhhJQRdbYyR9bfRsfS4HG8NtW/dStlvXW18tLZHX/4HfozTExgE+Y4ISYWAP11vC/HaNA201wp6SbPs74udJ/Js+QHZXlItAhMnKvAEjKVICRyXchHVWYXTUnyz1h6axTU8RzzRejiSbMoBNSQJRAvhJ5c=
  - secure: uuLFEYHAujFjpgYsIGSJ/Vp8KcyUXmPOObnf3zyWKnRFoE6JGVCK/PvWihv1uhba9v5wW4jSq2hcxhBVzOR0HBBjgs4X5HKZV827Hk9ApF/WJydu/LtwrZy/UwyydPR3fwUo0+EU99h1pFY7BO8L7IPYtDklJUaayGQa2b6dIyeRUEI8iD5IuJ3S8OmhwgoOhMIwo6JuG1pCtOqdvsnR81sbx7XD4A5Tz3hZ0R8qcjfYDEoG5Z+4cFE+nA3b6iQcHk1R/jA4vxAmzfGognVBjYXbpwVhKA2+i5JhqhAajFK1tpEVRZg+qsL5eNMAT5zSONyTyUPCBBcCO0/zyJMUgO/D+UCPjFPCUAhQTn66HOYXrWLSs4GWozUc/yiyjtmu7s1Qz9X7+J0uCYPrCDk1dLnkCpIQ+LsIECG1sJmBGzh91ZVkrardL/rumhtqF2oZ1XGDA70WpP53NUzORcDw9eoK9rEG6xpJG6IxqqWS8wH9ITVixopFV/o1DAGqAJRgV0kzf5c4qtwp93hC1eYmfrSRe1ksPTx+Tj3og5XD3N0WE06cjsYJW5AMWX5YgH+Y1xRdHO9Q+tu4r29of5ANgnGRYIW8KWEwZFVr6gmdm498wTYPsY1nkn7dSKzkYAFmLYt0HKjhGHoFsNHkwVKEDW8FzQJKQyOybnwJT5ps87k=
